### ISSUE TITLE
怎么导入汉化包呢？

### ISSUE THREAD

**Issue by flycj** [pluwen/propresenter-cn#1]
如题

**Comment by pluwen** [comment]
readme 已更新
现在汉化还很不完整，欢迎贡献

**Comment by flycj** [comment]
好的， 你是购买的正版软件吗，还是使用的破解版呢？， 如果是破解的，有链接吗？我google 上没找到，都是v6的，v7 的都是windows资源，没有mac 的资源

**Comment by pluwen** [comment]
仅提供汉化包
